import { camelCase, writeFile } from './helpers.js';

const PKG = 'com.hospital';

export function generateConfig(schemaAST, symbolTable, outputDir) {
    console.log('\n⚙️  Backend — Configuration');

    // ── pom.xml ────────────────────────────────────────────────
    writeFile(outputDir, 'backend/pom.xml', `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
    </parent>

    <groupId>com.hospital</groupId>
    <artifactId>${camelCase(schemaAST.name)}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>${schemaAST.name}</name>
    <description>Generated by Hospital-DSL Compiler</description>

    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <!-- Spring Boot Starters -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <!-- PostgreSQL -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- JWT -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>0.11.5</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>0.11.5</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <version>0.11.5</version>
            <scope>runtime</scope>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
`);

    // ── application.properties ─────────────────────────────────
    const expiry = schemaAST.auth?.expiry || '7d';
    const ms = parseExpiry(expiry);

    writeFile(outputDir, 'backend/src/main/resources/application.properties', `# Generated by Hospital-DSL Compiler
spring.application.name=${schemaAST.name}

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/${camelCase(schemaAST.name)}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=hospital-dsl-generated-secret-change-me-in-production-please
jwt.expiration-ms=${ms}

# Server
server.port=8080
`);

    // ── Main Application class ─────────────────────────────────
    writeFile(outputDir, 'backend/src/main/java/com/hospital/HospitalApplication.java', `package ${PKG};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class HospitalApplication {
    public static void main(String[] args) {
        SpringApplication.run(HospitalApplication.class, args);
    }
}
`);

    // ── BeanUtils helper (getNullPropertyNames) ────────────────
    writeFile(outputDir, 'backend/src/main/java/com/hospital/util/BeanHelper.java', `package ${PKG}.util;

import org.springframework.beans.BeanWrapper;
import org.springframework.beans.BeanWrapperImpl;
import java.util.*;

public class BeanHelper {
    public static String[] getNullPropertyNames(Object source) {
        final BeanWrapper wrapper = new BeanWrapperImpl(source);
        Set<String> nullNames = new HashSet<>();
        for (var pd : wrapper.getPropertyDescriptors()) {
            if (wrapper.getPropertyValue(pd.getName()) == null) {
                nullNames.add(pd.getName());
            }
        }
        return nullNames.toArray(new String[0]);
    }
}
`);
}

function parseExpiry(expiry) {
    const match = expiry.match(/^(\d+)([dhms])$/);
    if (!match) return 604800000; // default 7d
    const val = parseInt(match[1]);
    switch (match[2]) {
        case 'd': return val * 86400000;
        case 'h': return val * 3600000;
        case 'm': return val * 60000;
        case 's': return val * 1000;
        default: return 604800000;
    }
}
