import path from 'path';
import fs from 'fs';

import { generateEntities }     from './backend/entityGen.js';
import { generateRepositories } from './backend/repoGen.js';
import { generateServices }     from './backend/serviceGen.js';
import { generateControllers }  from './backend/controllerGen.js';
import { generateSecurity }     from './backend/securityGen.js';
import { generateConfig }       from './backend/configGen.js';

import { generateScaffold }     from './frontend/scaffoldGen.js';
import { generateApiService }   from './frontend/apiServiceGen.js';
import { generateAuth }         from './frontend/authGen.js';
import { generateLayouts }      from './frontend/layoutGen.js';
import { generatePages }        from './frontend/pageGen.js';
import { generateContainers }   from './frontend/containerGen.js';
import { generateApp }          from './frontend/appGen.js';

export function generate(schemaAST, viewsAST, symbolTable) {
  const outputDir = path.resolve(import.meta.dirname, '../../generated');

  // Clean previous output
  if (fs.existsSync(outputDir)) {
    fs.rmSync(outputDir, { recursive: true });
  }
  fs.mkdirSync(outputDir, { recursive: true });

  console.log('\n' + '━'.repeat(55));
  console.log(`🏥 Generating Full-Stack App for: ${schemaAST.name}`);
  console.log('━'.repeat(55));

  // ── Backend ──────────────────────────────────────────────
  generateConfig(schemaAST, symbolTable, outputDir);
  generateEntities(schemaAST, symbolTable, outputDir);
  generateRepositories(schemaAST, symbolTable, outputDir);
  generateServices(schemaAST, symbolTable, outputDir);
  generateControllers(schemaAST, symbolTable, outputDir);
  generateSecurity(schemaAST, symbolTable, viewsAST, outputDir);

  // ── Frontend ─────────────────────────────────────────────
  generateScaffold(schemaAST, outputDir);
  generateApiService(schemaAST, symbolTable, outputDir);
  generateAuth(schemaAST, viewsAST, outputDir);
  generateLayouts(viewsAST, outputDir);
  generateContainers(outputDir);
  generatePages(viewsAST, schemaAST, symbolTable, outputDir);
  generateApp(viewsAST, outputDir);

  // ── README ───────────────────────────────────────────────
  generateReadme(schemaAST, viewsAST, symbolTable, outputDir);

  console.log('\n' + '━'.repeat(55));
  console.log('✅ Generation complete!\n');
  console.log('📋 Next steps:');
  console.log('   Backend:');
  console.log(`   1. Create PostgreSQL database: createdb ${schemaAST.name.charAt(0).toLowerCase() + schemaAST.name.slice(1)}`);
  console.log('   2. Update generated/backend/src/main/resources/application.properties');
  console.log('   3. cd generated/backend && mvn spring-boot:run\n');
  console.log('   Frontend:');
  console.log('   4. cd generated/frontend && npm install && npm run dev');
  console.log('   5. Open http://localhost:5173\n');
}

function generateReadme(schemaAST, viewsAST, symbolTable, outputDir) {
  const modules = Array.from(symbolTable.modules.entries())
    .map(([id, m]) => `| ${id} | ${m.fields.size} | ${m.apis.size} |`).join('\n');

  const portals = viewsAST?.portals.map(p =>
    `| ${p.name} | ${p.roles.join(', ')} | ${p.pages.length} |`
  ).join('\n') || 'No views file provided.';

  const content = `# ${schemaAST.name}

> Generated by Hospital-DSL Compiler

## Tech Stack
- **Backend**: Spring Boot 3.2 + PostgreSQL + Spring Security (JWT)
- **Frontend**: React 18 + Vite + React Router

## Modules

| Module | Fields | API Endpoints |
|--------|--------|--------------|
${modules}

## Portals

| Portal | Roles | Pages |
|--------|-------|-------|
${portals}

## Quick Start

### Backend
\`\`\`bash
# Create PostgreSQL database
createdb ${schemaAST.name.charAt(0).toLowerCase() + schemaAST.name.slice(1)}

# Edit connection settings
# generated/backend/src/main/resources/application.properties

# Run
cd backend
mvn spring-boot:run
\`\`\`

### Frontend
\`\`\`bash
cd frontend
npm install
npm run dev
# Open http://localhost:5173
\`\`\`

### First Admin Account
\`\`\`bash
curl -X POST http://localhost:8080/api/auth/register \\
  -H "Content-Type: application/json" \\
  -d '{"email":"admin@example.com","password":"Admin@123","role":"Admin","name":"Administrator"}'
\`\`\`
`;

  fs.writeFileSync(path.join(outputDir, 'README.md'), content);
  console.log('  📄 README.md');
}
