import { writeFile } from '../backend/helpers.js';

export function generateScaffold(schemaAST, outputDir) {
  console.log('\n📦 Frontend — Scaffold');

  writeFile(outputDir, 'frontend/package.json', JSON.stringify({
    name: schemaAST.name.toLowerCase() + '-frontend',
    private: true,
    version: '0.0.1',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview'
    },
    dependencies: {
      'react': '^18.2.0',
      'react-dom': '^18.2.0',
      'react-router-dom': '^6.22.0',
      'axios': '^1.6.0',
    },
    devDependencies: {
      '@vitejs/plugin-react': '^4.2.0',
      'vite': '^5.1.0',
      '@types/react': '^18.2.0',
    }
  }, null, 2));

  writeFile(outputDir, 'frontend/vite.config.js', `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
      }
    }
  }
});
`);

  writeFile(outputDir, 'frontend/index.html', `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${schemaAST.name}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.jsx"></script>
</body>
</html>
`);

  writeFile(outputDir, 'frontend/src/main.jsx', `import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import { AuthProvider } from './auth/AuthContext';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <BrowserRouter>
      <AuthProvider>
        <App />
      </AuthProvider>
    </BrowserRouter>
  </React.StrictMode>
);
`);

  // ── CSS Design System ──────────────────────────────────────
  writeFile(outputDir, 'frontend/src/index.css', `/* Generated by Hospital-DSL Compiler */
:root {
  --bg-primary: #0f1117;
  --bg-secondary: #1a1d27;
  --bg-card: #222533;
  --bg-hover: #2a2d3d;
  --border: #2e3144;
  --text-primary: #e8eaed;
  --text-secondary: #9aa0b0;
  --text-muted: #6b7280;
  --accent: #6366f1;
  --accent-hover: #818cf8;
  --accent-subtle: rgba(99,102,241,0.12);
  --success: #22c55e;
  --warning: #f59e0b;
  --danger: #ef4444;
  --radius: 10px;
  --radius-sm: 6px;
  --shadow: 0 4px 24px rgba(0,0,0,0.25);
  --transition: 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  --font: 'Inter', -apple-system, sans-serif;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: var(--font);
  background: var(--bg-primary);
  color: var(--text-primary);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}

/* ── Layout ───────────────────────────────────────── */
.app-layout { display: flex; min-height: 100vh; }

.sidebar {
  width: 260px; background: var(--bg-secondary); border-right: 1px solid var(--border);
  display: flex; flex-direction: column; padding: 1.5rem 0;
  position: fixed; top: 0; left: 0; bottom: 0; z-index: 10;
}

.sidebar-logo {
  padding: 0 1.5rem 1.5rem; font-size: 1.25rem; font-weight: 700;
  color: var(--accent); border-bottom: 1px solid var(--border);
  margin-bottom: 1rem; letter-spacing: -0.02em;
}

.sidebar-nav { flex: 1; display: flex; flex-direction: column; gap: 2px; padding: 0 0.75rem; }

.sidebar-link {
  display: flex; align-items: center; gap: 0.75rem; padding: 0.7rem 1rem;
  border-radius: var(--radius-sm); color: var(--text-secondary);
  text-decoration: none; font-size: 0.9rem; font-weight: 500;
  transition: var(--transition);
}
.sidebar-link:hover { background: var(--bg-hover); color: var(--text-primary); }
.sidebar-link.active { background: var(--accent-subtle); color: var(--accent); }

.sidebar-footer {
  padding: 1rem 1.5rem; border-top: 1px solid var(--border);
  margin-top: auto; display: flex; justify-content: space-between; align-items: center;
}

.main-content { margin-left: 260px; flex: 1; padding: 2rem; }
.page-header { margin-bottom: 2rem; }
.page-header h1 { font-size: 1.75rem; font-weight: 700; letter-spacing: -0.03em; }

/* ── Cards ────────────────────────────────────────── */
.card {
  background: var(--bg-card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 1.5rem;
  box-shadow: var(--shadow); margin-bottom: 1.5rem;
}

/* ── Buttons ──────────────────────────────────────── */
.btn {
  display: inline-flex; align-items: center; gap: 0.5rem;
  padding: 0.6rem 1.2rem; border-radius: var(--radius-sm);
  font-size: 0.875rem; font-weight: 600; cursor: pointer;
  border: none; transition: var(--transition); font-family: var(--font);
}
.btn-primary { background: var(--accent); color: white; }
.btn-primary:hover { background: var(--accent-hover); transform: translateY(-1px); }
.btn-danger { background: var(--danger); color: white; }
.btn-danger:hover { opacity: 0.9; }
.btn-ghost {
  background: transparent; color: var(--text-secondary); border: 1px solid var(--border);
}
.btn-ghost:hover { background: var(--bg-hover); color: var(--text-primary); }
.btn-sm { padding: 0.35rem 0.75rem; font-size: 0.8rem; }

/* ── Tables ───────────────────────────────────────── */
.data-table { width: 100%; border-collapse: collapse; }
.data-table th {
  text-align: left; padding: 0.75rem 1rem; font-size: 0.75rem;
  font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;
  color: var(--text-muted); border-bottom: 1px solid var(--border);
}
.data-table td {
  padding: 0.85rem 1rem; border-bottom: 1px solid var(--border);
  font-size: 0.9rem; color: var(--text-secondary);
}
.data-table tr:hover td { background: var(--bg-hover); color: var(--text-primary); }

/* ── Forms ────────────────────────────────────────── */
.form-group { margin-bottom: 1.25rem; }
.form-label {
  display: block; font-size: 0.8rem; font-weight: 600;
  color: var(--text-secondary); margin-bottom: 0.4rem; text-transform: uppercase;
  letter-spacing: 0.04em;
}
.form-input, .form-select, .form-textarea {
  width: 100%; padding: 0.7rem 1rem; background: var(--bg-primary);
  border: 1px solid var(--border); border-radius: var(--radius-sm);
  color: var(--text-primary); font-size: 0.9rem; font-family: var(--font);
  transition: var(--transition);
}
.form-input:focus, .form-select:focus, .form-textarea:focus {
  outline: none; border-color: var(--accent);
  box-shadow: 0 0 0 3px var(--accent-subtle);
}
.form-textarea { min-height: 100px; resize: vertical; }

/* ── Metric Grid ──────────────────────────────────── */
.metric-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
.metric-card {
  background: var(--bg-card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 1.25rem 1.5rem;
  display: flex; flex-direction: column; gap: 0.3rem;
}
.metric-label { font-size: 0.8rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.04em; }
.metric-value { font-size: 2rem; font-weight: 700; color: var(--text-primary); letter-spacing: -0.03em; }

/* ── Modal / Drawer ───────────────────────────────── */
.modal-overlay {
  position: fixed; inset: 0; background: rgba(0,0,0,0.6);
  display: flex; align-items: center; justify-content: center; z-index: 100;
  backdrop-filter: blur(4px);
}
.modal-content {
  background: var(--bg-secondary); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 2rem; max-width: 600px;
  width: 90%; max-height: 85vh; overflow-y: auto; box-shadow: var(--shadow);
}
.modal-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem; }
.modal-header h2 { font-size: 1.25rem; font-weight: 700; }
.modal-close { background: none; border: none; color: var(--text-muted); font-size: 1.5rem; cursor: pointer; }

/* ── Status badges ────────────────────────────────── */
.badge {
  display: inline-flex; padding: 0.2rem 0.65rem; border-radius: 999px;
  font-size: 0.75rem; font-weight: 600; letter-spacing: 0.02em;
}
.badge-success { background: rgba(34,197,94,0.15); color: var(--success); }
.badge-warning { background: rgba(245,158,11,0.15); color: var(--warning); }
.badge-danger  { background: rgba(239,68,68,0.15);  color: var(--danger); }
.badge-default { background: var(--accent-subtle); color: var(--accent); }

/* ── Auth Pages ───────────────────────────────────── */
.auth-page {
  min-height: 100vh; display: flex; align-items: center; justify-content: center;
  background: var(--bg-primary);
}
.auth-card {
  background: var(--bg-secondary); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 2.5rem; width: 420px;
  box-shadow: var(--shadow);
}
.auth-card h1 { font-size: 1.5rem; font-weight: 700; margin-bottom: 0.5rem; text-align: center; }
.auth-card p { color: var(--text-muted); text-align: center; margin-bottom: 2rem; font-size: 0.9rem; }
.auth-tabs { display: flex; gap: 0; margin-bottom: 1.5rem; border-radius: var(--radius-sm); overflow: hidden; border: 1px solid var(--border); }
.auth-tab {
  flex: 1; padding: 0.6rem; text-align: center; cursor: pointer; font-size: 0.85rem;
  font-weight: 600; background: var(--bg-primary); color: var(--text-muted);
  border: none; transition: var(--transition);
}
.auth-tab.active { background: var(--accent); color: white; }
.auth-link { color: var(--accent); text-decoration: none; font-size: 0.85rem; }
.auth-link:hover { text-decoration: underline; }

/* ── Calendar ─────────────────────────────────────── */
.calendar-grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 1px; background: var(--border); border-radius: var(--radius); overflow: hidden; }
.calendar-header { background: var(--bg-secondary); padding: 0.5rem; text-align: center; font-size: 0.75rem; font-weight: 600; color: var(--text-muted); }
.calendar-cell { background: var(--bg-card); min-height: 100px; padding: 0.5rem; }
.calendar-cell.today { border: 2px solid var(--accent); }
.calendar-day { font-size: 0.8rem; font-weight: 600; color: var(--text-muted); margin-bottom: 0.25rem; }
.calendar-event { font-size: 0.7rem; padding: 0.2rem 0.4rem; background: var(--accent-subtle); color: var(--accent); border-radius: 3px; margin-bottom: 2px; cursor: pointer; }

/* ── Kanban ────────────────────────────────────────── */
.kanban-board { display: flex; gap: 1rem; overflow-x: auto; padding-bottom: 1rem; }
.kanban-column { min-width: 280px; flex: 1; background: var(--bg-secondary); border-radius: var(--radius); padding: 1rem; }
.kanban-column-title { font-size: 0.85rem; font-weight: 700; color: var(--text-muted); text-transform: uppercase; margin-bottom: 1rem; }
.kanban-card { background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius-sm); padding: 0.75rem; margin-bottom: 0.5rem; cursor: pointer; }
.kanban-card:hover { border-color: var(--accent); }

/* ── Responsive ───────────────────────────────────── */
@media (max-width: 768px) {
  .sidebar { display: none; }
  .main-content { margin-left: 0; }
}

/* ── Utility ──────────────────────────────────────── */
.flex { display: flex; }
.gap-1 { gap: 0.5rem; }
.gap-2 { gap: 1rem; }
.mt-1 { margin-top: 0.5rem; }
.mt-2 { margin-top: 1rem; }
.text-center { text-align: center; }
.text-muted { color: var(--text-muted); }
`);
}
